import math
#v1.1 this calculator calculates the quadratic formula (QF)
#v1.2 vertex finder (VTXF) added (-b/2a) Finished 1/27/2026
#v1.3 the formula is incorrect, now it is fixed
#v1.4 Linear Formula added (LF)
import time
print("Welcome to Python Quadratics Calulator v1.3!")
time.sleep(1.5)
print("Remember the form of the Quadratic equaion we are using: AX^2 + BX + c")
print("We have the Quadratic Formula, Vertex finder (VTXF), and the Linear formula (LF)")
time.sleep(1.5)
print("QF: (X=-b+ or - sq root of B^2 - 4ac)/2a ")
print("Type QF for quadratic formula")
time.sleep(1.5)
#the calculator runs 2 equations one with b+ and one with b-
input("Type QF or VTXF on next line:")
var=input()
if var==("QF"):
    print("Quadratic Formula Selected")
    print("Loading Variables...")
    time.sleep(1.5)
    print("Variables loaded")
    input("Type value of b on next line:")
    b=int(input())
    input("Type value of a on next line:")
    a=int(input())
    input("Type value of c on next line:")
    c=int(input())
    time.sleep(1.5)
    print("Running Code...")
    time.sleep(1.5)
    w= math.pow(b,2) -4*a*c
    print(w)
    e=w**(0.5) 
    print(e)
    r=(-b + e) / (2*a)
    print("X=",r)
    u=(-b-e) / (2*a)
    print("X=",u)
if var==("VTXF"):
    print("Vertex Finder Seleced")
    print("Loading Vaiables...")
    time.sleep(1.5)
    print("Variables Loaded")
    input("type value of A on Next line")
    A=int(input())
    input("Type value of B on Next Line")
    B=int(input())
    time.sleep(1.5)
    X= (-1 * B) / (2 * A)
    #Debugging Tool
    print("The X value of the vertex is", X)
    print("Loading Equations...")
    time.sleep(1.5)
    print("Equation Loaded")
    print("Type in the a,b, and c values of the Quadratic Equation")
    input("Type value of a on next line")
    J=int(input())
    input("Type value of b on next line")
    K=int(input())
    input("Type value of c on next line")
    L=int(input())
    T= math.pow(X,2)
    #Debugging Tool
    print(T)
    Y= T * J + K * X + L
    #Debugging tool
    print("The Y value of the Vertex is", Y)
    print("The vertex is", (X , Y))
if var==("LF"):
    print("Linear Formula selected")
    time.sleep(1)
    print("Loading Complete")
    print("Linear Formula: Incomplete)
    a=input("Value of a: ")